from .classifier import ClassifierResNet
from .segmentation_head import MultiPartSegHeadResNet, SceneSegHeadResNet
from .multi_dimensional_head import MultiDimHeadResNet
from .discriminator_head import DiscriminatorHead
